import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import Footer from '@/components/layout/footer';
import Navbar from '@/components/layout/navbar';
import GotopButton from '@/components/gotoTop';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-white'>
        <Navbar />
        {children}
        <Toaster />
        <Footer />
        <GotopButton />
      </body>
    </html>
  );
}
